use crate::approved_sentence_formatters::dpt::DPT;
use crate::approved_sentence_formatters::gga::GGA;
use crate::approved_sentence_formatters::gsa::GSA;
use crate::NMEASentenceFormatter;

pub mod dpt;
pub mod gga;
pub mod gsa;

pub enum SentenceContent {
    DPT(DPT),
    GSA(GSA),
    GGA(GGA),
    TODO,
}

pub fn select_sentence_formatter(
    formatter: &NMEASentenceFormatter,
    fields: Vec<&[u8]>,
) -> SentenceContent {
    match formatter {
        ['A', 'A', 'M'] => SentenceContent::TODO,
        ['A', 'B', 'K'] => SentenceContent::TODO,
        ['A', 'B', 'M'] => SentenceContent::TODO,
        ['A', 'C', 'A'] => SentenceContent::TODO,
        ['A', 'C', 'K'] => SentenceContent::TODO,
        ['A', 'C', 'S'] => SentenceContent::TODO,
        ['A', 'I', 'R'] => SentenceContent::TODO,
        ['A', 'L', 'M'] => SentenceContent::TODO,
        ['A', 'L', 'R'] => SentenceContent::TODO,
        ['A', 'P', 'B'] => SentenceContent::TODO,
        ['B', 'B', 'M'] => SentenceContent::TODO,
        ['B', 'E', 'C'] => SentenceContent::TODO,
        ['B', 'O', 'D'] => SentenceContent::TODO,
        ['B', 'W', 'C'] => SentenceContent::TODO,
        ['B', 'W', 'R'] => SentenceContent::TODO,
        ['B', 'W', 'W'] => SentenceContent::TODO,
        ['C', 'U', 'R'] => SentenceContent::TODO,
        ['D', 'B', 'T'] => SentenceContent::TODO,
        ['D', 'C', 'N'] => SentenceContent::TODO,
        ['D', 'P', 'T'] => SentenceContent::DPT(DPT::from_field(fields)),
        ['D', 'S', 'C'] => SentenceContent::TODO,
        ['D', 'S', 'E'] => SentenceContent::TODO,
        ['D', 'S', 'I'] => SentenceContent::TODO,
        ['D', 'S', 'R'] => SentenceContent::TODO,
        ['D', 'T', 'M'] => SentenceContent::TODO,
        ['F', 'S', 'I'] => SentenceContent::TODO,
        ['G', 'B', 'S'] => SentenceContent::TODO,
        ['G', 'G', 'A'] => SentenceContent::GGA(GGA::from_field(fields)),
        ['G', 'L', 'C'] => SentenceContent::TODO,
        ['G', 'L', 'L'] => SentenceContent::TODO,
        ['G', 'M', 'P'] => SentenceContent::TODO,
        ['G', 'N', 'S'] => SentenceContent::TODO,
        ['G', 'R', 'S'] => SentenceContent::TODO,
        ['G', 'S', 'A'] => SentenceContent::GSA(GSA::from_field(fields)),
        ['G', 'S', 'T'] => SentenceContent::TODO,
        ['G', 'S', 'V'] => SentenceContent::TODO,
        ['H', 'D', 'G'] => SentenceContent::TODO,
        ['H', 'D', 'T'] => SentenceContent::TODO,
        ['H', 'M', 'R'] => SentenceContent::TODO,
        ['H', 'M', 'S'] => SentenceContent::TODO,
        ['H', 'S', 'C'] => SentenceContent::TODO,
        ['H', 'T', 'C'] => SentenceContent::TODO,
        ['H', 'T', 'D'] => SentenceContent::TODO,
        ['L', 'C', 'D'] => SentenceContent::TODO,
        ['L', 'R', '1'] => SentenceContent::TODO,
        ['L', 'R', '2'] => SentenceContent::TODO,
        ['L', 'R', '3'] => SentenceContent::TODO,
        ['L', 'R', 'F'] => SentenceContent::TODO,
        ['L', 'R', 'I'] => SentenceContent::TODO,
        ['M', 'L', 'A'] => SentenceContent::TODO,
        ['M', 'S', 'K'] => SentenceContent::TODO,
        ['M', 'S', 'S'] => SentenceContent::TODO,
        ['M', 'T', 'W'] => SentenceContent::TODO,
        ['M', 'W', 'D'] => SentenceContent::TODO,
        ['M', 'W', 'V'] => SentenceContent::TODO,
        ['O', 'S', 'D'] => SentenceContent::TODO,
        ['R', 'M', 'A'] => SentenceContent::TODO,
        ['R', 'M', 'B'] => SentenceContent::TODO,
        ['R', 'M', 'C'] => SentenceContent::TODO,
        ['R', 'O', 'T'] => SentenceContent::TODO,
        ['R', 'P', 'M'] => SentenceContent::TODO,
        ['R', 'S', 'A'] => SentenceContent::TODO,
        ['R', 'S', 'D'] => SentenceContent::TODO,
        ['R', 'T', 'E'] => SentenceContent::TODO,
        ['S', 'F', 'I'] => SentenceContent::TODO,
        ['S', 'S', 'D'] => SentenceContent::TODO,
        ['S', 'T', 'N'] => SentenceContent::TODO,
        ['T', 'L', 'B'] => SentenceContent::TODO,
        ['T', 'L', 'L'] => SentenceContent::TODO,
        ['T', 'T', 'M'] => SentenceContent::TODO,
        ['T', 'U', 'T'] => SentenceContent::TODO,
        ['T', 'X', 'T'] => SentenceContent::TODO,
        ['V', 'B', 'W'] => SentenceContent::TODO,
        ['V', 'D', 'M'] => SentenceContent::TODO,
        ['V', 'D', 'O'] => SentenceContent::TODO,
        ['V', 'D', 'R'] => SentenceContent::TODO,
        ['V', 'H', 'W'] => SentenceContent::TODO,
        ['V', 'L', 'W'] => SentenceContent::TODO,
        ['V', 'P', 'W'] => SentenceContent::TODO,
        ['V', 'S', 'D'] => SentenceContent::TODO,
        ['V', 'T', 'G'] => SentenceContent::TODO,
        ['W', 'C', 'V'] => SentenceContent::TODO,
        ['W', 'N', 'C'] => SentenceContent::TODO,
        ['W', 'P', 'L'] => SentenceContent::TODO,
        ['X', 'D', 'R'] => SentenceContent::TODO,
        ['X', 'T', 'E'] => SentenceContent::TODO,
        ['X', 'T', 'R'] => SentenceContent::TODO,
        ['Z', 'D', 'A'] => SentenceContent::TODO,
        ['Z', 'D', 'L'] => SentenceContent::TODO,
        ['Z', 'F', 'O'] => SentenceContent::TODO,
        ['Z', 'T', 'G'] => SentenceContent::TODO,
        _ => SentenceContent::TODO,
    }
}
